gsub_file 'config/routes.rb', /\n  get \"home\/index\"\n/, ''
gsub_file 'config/routes.rb', /\n  get \"users\/index\"\n/, ''
gsub_file 'config/routes.rb', /\n  get \"users\/new\"\n/, ''
gsub_file 'config/routes.rb', /\n  get \"users\/create\"\n/, ''
gsub_file 'config/routes.rb', /\n  get \"users\/edit\"\n/, ''
gsub_file 'config/routes.rb', /\n  get \"users\/update\"\n/, ''
gsub_file 'config/routes.rb', /\n  get \"users\/destroy\"\n/, ''
gsub_file 'config/routes.rb', /\n  get \"dashboard\/index\"\n/, ''
